source_file='/home/目标文件.tgz'
#目标文件在当前目录下，文件名在原始文件名字前面加上copy
dest_file='copy-'+source_file[source_file.rfind('/')+1:]
print('目标文件名字：%s'%dest_file)
#打开文件
source_file=open(source_file,'rb')
dest_file=open('dest_file','w')
#读取文件内容
content=source_file.read()
#把读取的目标文件的内容写到目标文件中
dest_file.write(content)
#关闭文件
source_file.close()
dest.file.close()
